apiVersion: v1
kind: Service
metadata:
  name: test-app-service
  labels:
    app: test-app
    type: back-end
spec:
  type: NodePort
  selector:
    app: test-app
    type: back-end
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deployment
  labels:
    app: test-app
    type: back-end
spec:
  template:
    metadata:
      name: test-app-pod
      labels:
        app: test-app
        type: back-end
    spec:
      containers:
        - name: test-app-container
          image: test-app-skaffold:latest
  replicas: 1
  selector:
    matchLabels:
      type: back-end
