apiVersion: v1
kind: Service
metadata:
  name: kuber-service
  labels:
    app: kuber
    type: back-end
spec:
  type: NodePort
  selector:
    app: kuber
    type: back-end
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
